// front_end-frameworks/react/src/sections/Contact.jsx
import { FolderCode, Users, Sparkles, User, AtSign, Mail } from 'lucide-react';

function About() {
  return (
    <section id="about-section" className="relative bg-black py-24">
      <div className="mx-auto flex max-w-6xl flex-col items-center gap-8 px-6 text-center">
        {/* Badge */}
        <div className="flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-4 py-2 text-sm font-medium text-violet-300">
          ✧ Strat your AI journey ? ✧
        </div>

        {/* Title */}
        <div>
          <h2 className="text-5xl leading-none font-black tracking-tight md:text-7xl">
            <span className="block text-slate-50">Ready to Explore</span>
            <span className="block text-violet-300">Agentic AI ?</span>
          </h2>
        </div>

        {/* CTA */}
        <div className="flex flex-col items-center gap-4 sm:flex-row">
          <a
            href="#contact-section"
            className="rounded-md bg-violet-500 px-4 py-2 text-sm font-semibold text-slate-50 shadow-lg shadow-violet-500/40 transition-colors hover:bg-violet-600 md:text-base"
          >
            Enroll at Holberton School ➔
          </a>

          <a
            href="#features-section"
            className="rounded-md border border-slate-800 bg-slate-950 px-4 py-2 text-sm font-semibold text-slate-50 transition-colors hover:bg-slate-900 md:text-base"
          >
            Need more information ?
          </a>
        </div>

        {/* Highlights */}
        <div className="flex items-center gap-10">
          <div className="flex items-center gap-2">
            <FolderCode className="text-violet-500" size={16} />
            <span className="text-slate-500">Project-based learning</span>
          </div>

          <div className="flex items-center gap-2">
            <Users className="text-violet-500" size={16} />
            <span className="text-slate-500">Peer learning environment</span>
          </div>

          <div className="flex items-center gap-2">
            <Sparkles className="text-violet-500" size={16} />
            <span className="text-slate-500">AI-powered workflows</span>
          </div>
        </div>

        {/* Contact Form */}
        <div className="mt-8 w-full max-w-2xl rounded-3xl border border-slate-800 bg-slate-950/80 p-8 shadow-2xl shadow-slate-950/40 backdrop-blur">
          <form className="flex flex-col gap-6">
            {/* Full name */}
            <div className="text-left">
              <label className="mb-2 flex items-center gap-2 font-semibold text-slate-50">
                <User className="h-5 w-5 text-violet-500" />
                Full name
              </label>

              <input
                type="text"
                placeholder="Your full name..."
                className="w-full rounded-lg border border-slate-800 bg-black px-4 py-3 text-slate-100 placeholder:text-slate-500 focus:border-violet-500 focus:outline-none"
              />
            </div>

            {/* Email */}
            <div className="text-left">
              <label className="mb-2 flex items-center gap-2 font-semibold text-slate-50">
                <AtSign className="h-5 w-5 text-violet-500" />
                Email
              </label>

              <input
                type="email"
                placeholder="you@example.com"
                className="w-full rounded-lg border border-slate-800 bg-black px-4 py-3 text-slate-100 placeholder:text-slate-500 focus:border-violet-500 focus:outline-none"
              />
            </div>

            {/* Message */}
            <div className="text-left">
              <label className="mb-2 flex items-center gap-2 font-semibold text-slate-50">
                <Mail className="h-5 w-5 text-violet-500" />
                Message
              </label>

              <textarea
                rows={5}
                placeholder="Tell us about your project or learning goals!"
                className="w-full resize-none rounded-lg border border-slate-800 bg-black px-4 py-3 text-slate-100 placeholder:text-slate-500 focus:border-violet-500 focus:outline-none"
              />
            </div>

            {/* Button */}
            <button
              type="submit"
              className="rounded-lg bg-violet-500 px-6 py-3 font-semibold text-white transition-colors hover:bg-violet-600"
            >
              Send message
            </button>
          </form>
        </div>
      </div>
    </section>
  );
}

export default About;

// front_end-frameworks/vue/src/components/sections/Contact.vue
<script setup>
import { reactive, ref, computed } from 'vue'
import { FolderCode, Users, Sparkles, User, AtSign, Mail } from 'lucide-vue-next'
import SectionBadge from '../ui/SectionBadge.vue'
import SectionTitle from '../ui/SectionTitle.vue'
import Button from '../ui/Button.vue'

const DEFAULT_FEEDBACK = 'Fill in the form and we will get back to you shortly.'

/* Form data, sending state and dynamic feedback message. */
const formData = reactive({
  fullName: '',
  email: '',
  message: '',
})
const isSending = ref(false)
const feedback = ref(DEFAULT_FEEDBACK)
const focusedField = ref(null)

/* Basic frontend validation (must also be done on the backend in real apps). */
const isNameValid = computed(() => formData.fullName.trim().length >= 2)
const isEmailValid = computed(() => formData.email.includes('@') && formData.email.includes('.'))
const isMessageValid = computed(() => formData.message.trim().length >= 10)
const isFormValid = computed(() => isNameValid.value && isEmailValid.value && isMessageValid.value)

/* Border color only changes while the field is focused. */
function fieldBorderClass(fieldName, isValid) {
  if (focusedField.value !== fieldName) {
    return 'border-slate-800'
  }
  return isValid ? 'border-violet-500' : 'border-red-500'
}

async function handleSubmit() {
  isSending.value = true
  feedback.value = 'Sending your message...'

  /* Simulate a network request with a short delay. */
  await new Promise((resolve) => setTimeout(resolve, 1500))

  formData.fullName = ''
  formData.email = ''
  formData.message = ''
  isSending.value = false
  feedback.value = 'Message sent! We will reply to you soon.'

  /* Return to the default instruction after a short delay. */
  setTimeout(() => {
    feedback.value = DEFAULT_FEEDBACK
  }, 4000)
}
</script>

<template>
  <section id="contact-section" class="relative bg-black py-24">
    <div class="mx-auto flex max-w-6xl flex-col items-center gap-8 px-6 text-center">
      <!-- Badge -->
      <SectionBadge symbol="✧" class="text-sm font-medium"> Start your AI journey ? </SectionBadge>

      <!-- Title -->
      <div>
        <SectionTitle class="text-5xl md:text-7xl" top="Ready to Explore" bottom="Agentic AI ?" />
      </div>

      <!-- CTA -->
      <div class="flex flex-col items-center gap-4 sm:flex-row">
        <Button
          href="https://www.holbertonschool.fr/rejoindre-lhippocamp"
          external
          class="text-sm md:text-base"
        >
          Enroll at Holberton School ➔
        </Button>

        <Button href="#features-section" variant="secondary" class="text-sm md:text-base">
          Need more information ?
        </Button>
      </div>

      <!-- Highlights -->
      <div class="flex flex-col items-center gap-6 sm:flex-row sm:gap-10">
        <div class="flex items-center gap-2">
          <FolderCode class="text-violet-500" :size="16" />
          <span class="text-slate-400">Project-based learning</span>
        </div>

        <div class="flex items-center gap-2">
          <Users class="text-violet-500" :size="16" />
          <span class="text-slate-400">Peer learning environment</span>
        </div>

        <div class="flex items-center gap-2">
          <Sparkles class="text-violet-500" :size="16" />
          <span class="text-slate-400">AI-powered workflows</span>
        </div>
      </div>

      <!-- Contact Form -->
      <div
        class="mt-8 w-full max-w-2xl rounded-3xl border border-slate-800 bg-slate-950/80 p-8 shadow-2xl shadow-slate-950/40 backdrop-blur"
      >
        <form autocomplete="off" class="flex flex-col gap-6" @submit.prevent="handleSubmit">
          <!-- Full name -->
          <div class="text-left">
            <label for="fullName" class="mb-2 flex items-center gap-2 font-semibold text-slate-50">
              <User class="h-5 w-5 text-violet-500" />
              Full name
            </label>

            <input
              id="fullName"
              v-model="formData.fullName"
              name="fullName"
              type="text"
              autocomplete="off"
              placeholder="Your full name..."
              class="w-full rounded-lg border bg-black px-4 py-3 text-slate-100 placeholder:text-slate-500 focus:outline-none"
              :class="fieldBorderClass('fullName', isNameValid)"
              @focus="focusedField = 'fullName'"
              @blur="focusedField = null"
            />
          </div>

          <!-- Email -->
          <div class="text-left">
            <label for="email" class="mb-2 flex items-center gap-2 font-semibold text-slate-50">
              <AtSign class="h-5 w-5 text-violet-500" />
              Email
            </label>

            <input
              id="email"
              v-model="formData.email"
              name="email"
              type="email"
              autocomplete="off"
              placeholder="you@example.com"
              class="w-full rounded-lg border bg-black px-4 py-3 text-slate-100 placeholder:text-slate-500 focus:outline-none"
              :class="fieldBorderClass('email', isEmailValid)"
              @focus="focusedField = 'email'"
              @blur="focusedField = null"
            />
          </div>

          <!-- Message -->
          <div class="text-left">
            <label for="message" class="mb-2 flex items-center gap-2 font-semibold text-slate-50">
              <Mail class="h-5 w-5 text-violet-500" />
              Message
            </label>

            <textarea
              id="message"
              v-model="formData.message"
              name="message"
              :rows="5"
              autocomplete="off"
              placeholder="Tell us about your project or learning goals..."
              class="w-full resize-none rounded-lg border bg-black px-4 py-3 text-slate-100 placeholder:text-slate-500 focus:outline-none"
              :class="fieldBorderClass('message', isMessageValid)"
              @focus="focusedField = 'message'"
              @blur="focusedField = null"
            />
          </div>

          <!-- Button -->
          <button
            type="submit"
            :disabled="!isFormValid || isSending"
            class="rounded-lg bg-violet-500 px-6 py-3 font-semibold text-white transition-colors hover:bg-violet-600 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {{ isSending ? 'Sending...' : 'Send message' }}
          </button>

          <!-- Feedback message -->
          <p class="text-center text-sm text-slate-400">
            {{ feedback }}
          </p>
        </form>
      </div>
    </div>
  </section>
</template>
